# Run Rails server
#
# VERSION        0.0.1
# DOCKER-VERSION 0.4.8

# USAGE: docker build -t codemancers/basebox/ruby2 https://raw.github.com/deepak/Dockfiles/master/rails/Dockerfile

FROM codemancers/basebox/ruby2
 
MAINTAINER Deepak Kannan "deepak@codemancers.com"

